CREATE DATABASE entrepaginas_db;

\c entrepaginas_db;

CREATE TABLE diary_entries (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    entry_date DATE NOT NULL DEFAULT CURRENT_DATE,
    mood VARCHAR(50),
    tags TEXT[],
    photo TEXT,
    is_favorite BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO diary_entries (title, content, entry_date, mood, tags) VALUES
('Meu primeiro dia', 'Hoje foi um dia muito especial, o primeiro dia do meu diário digital! Estou animado para começar a documentar minha jornada.', '2024-01-01', 'feliz', ARRAY['primeiro-dia', 'especial', 'inicio']),
('Reflexões da manhã', 'Acordei pensando sobre os objetivos para este ano. Quero me dedicar mais aos estudos e cuidar melhor da minha saúde.', '2024-01-02', 'reflexivo', ARRAY['manha', 'objetivos', 'saude']),
('Um dia tranquilo', 'Hoje foi um dia calmo, sem muitos acontecimentos. Às vezes esses dias são os melhores para relaxar.', '2024-01-03', 'tranquilo', ARRAY['calmo', 'paz', 'relaxamento']),
('Aventura no parque', 'Saí para caminhar no parque hoje. A natureza sempre me traz uma sensação de paz e renovação.', '2024-01-04', 'energizado', ARRAY['natureza', 'caminhada', 'parque']),
('Dia de trabalho intenso', 'O trabalho esteve bem corrido hoje. Muitas reuniões e prazos apertados, mas consegui dar conta de tudo.', '2024-01-05', 'estressado', ARRAY['trabalho', 'reunioes', 'prazos']),
('Encontro com amigos', 'Encontrei meus amigos da faculdade hoje. Foi ótimo relembrar os velhos tempos e colocar o papo em dia.', '2024-01-06', 'alegre', ARRAY['amigos', 'faculdade', 'nostalgia']),
('Domingo de descanso', 'Domingo perfeito para ficar em casa, assistir filmes e não fazer nada produtivo. Às vezes é necessário.', '2024-01-07', 'relaxado', ARRAY['descanso', 'filmes', 'casa']),
('Nova descoberta', 'Descobri um novo hobby hoje: pintura! Comprei alguns materiais básicos e já fiz minha primeira obra.', '2024-01-08', 'entusiasmado', ARRAY['hobby', 'pintura', 'arte']),
('Dia chuvoso', 'Choveu o dia todo. Aproveitei para ler um livro que estava pendente há meses. A chuva tem algo de poético.', '2024-01-09', 'contemplativo', ARRAY['chuva', 'leitura', 'livro']),
('Reunião familiar', 'Almoço em família hoje. Sempre bom estar com as pessoas que amamos e compartilhar boas histórias.', '2024-01-10', 'grato', ARRAY['familia', 'almoco', 'amor']),
('Desafio superado', 'Consegui terminar aquele projeto difícil no trabalho. A sensação de conquista é indescritível!', '2024-01-11', 'realizado', ARRAY['projeto', 'conquista', 'trabalho']),
('Noite estrelada', 'Subi no terraço para observar as estrelas. O universo é tão vasto e misterioso. Me senti pequeno e grato.', '2024-01-12', 'inspirado', ARRAY['estrelas', 'universo', 'gratidao']),
('Aula de culinária', 'Tentei fazer uma receita nova hoje. Não ficou perfeita, mas foi divertido experimentar na cozinha.', '2024-01-13', 'divertido', ARRAY['culinaria', 'receita', 'experimenta']),
('Dia de folga', 'Finalmente um dia livre! Aproveitei para organizar o quarto e fazer aquela faxina que estava adiando.', '2024-01-14', 'produtivo', ARRAY['organizacao', 'limpeza', 'casa']),
('Conversa profunda', 'Tive uma conversa muito interessante com um colega sobre filosofia e propósito de vida. Me fez pensar muito.', '2024-01-15', 'pensativo', ARRAY['filosofia', 'proposito', 'conversa']),
('Exercício matinal', 'Acordei cedo para fazer exercícios. Começar o dia assim deixa tudo mais energizado e produtivo.', '2024-01-16', 'energizado', ARRAY['exercicio', 'manha', 'energia']),
('Visita ao museu', 'Fui ao museu de arte moderna. Algumas obras realmente me tocaram e me fizeram ver a arte de forma diferente.', '2024-01-17', 'inspirado', ARRAY['museu', 'arte', 'cultura']),
('Dia difícil', 'Hoje não foi um bom dia. Várias coisas deram errado, mas sei que amanhã será melhor. É importante aceitar os dias ruins.', '2024-01-18', 'triste', ARRAY['dificil', 'problemas', 'superacao']),
('Novo aprendizado', 'Comecei um curso online de programação. Sempre quis aprender e finalmente dei o primeiro passo!', '2024-01-19', 'motivado', ARRAY['curso', 'programacao', 'aprendizado']),
('Passeio na praia', 'Fui à praia no final da tarde. O som das ondas e o pôr do sol criaram um momento mágico de paz interior.', '2024-01-20', 'sereno', ARRAY['praia', 'por-do-sol', 'paz']),
('Reflexão noturna', 'Antes de dormir, sempre gosto de refletir sobre o dia. Hoje foi cheio de pequenas alegrias e aprendizados.', '2024-01-21', 'grato', ARRAY['reflexao', 'gratidao', 'aprendizado']),
('Projeto pessoal', 'Comecei a trabalhar em um projeto pessoal que tenho em mente há anos. É emocionante tirar ideias do papel!', '2024-01-22', 'empolgado', ARRAY['projeto', 'pessoal', 'ideias']),
('Encontro casual', 'Encontrei um antigo professor na rua hoje. Foi bom conversar e lembrar dos tempos de escola.', '2024-01-23', 'nostalgico', ARRAY['professor', 'escola', 'encontro']),
('Dia de spa caseiro', 'Decidi fazer um dia de autocuidado em casa. Máscara facial, banho relaxante e música suave.', '2024-01-24', 'relaxado', ARRAY['autocuidado', 'relaxamento', 'spa']),
('Inspiração literária', 'Li um poema hoje que me tocou profundamente. A literatura tem o poder de nos transformar por dentro.', '2024-01-25', 'tocado', ARRAY['poesia', 'literatura', 'inspiracao']),
('Caminhada matinal', 'Saí para caminhar bem cedo. As ruas vazias e o ar fresco da manhã me deram uma sensação de liberdade.', '2024-01-26', 'livre', ARRAY['caminhada', 'manha', 'liberdade']),
('Descoberta musical', 'Descobri uma banda nova que está fazendo meu estilo musical. A música é realmente universal.', '2024-01-27', 'animado', ARRAY['musica', 'banda', 'descoberta']),
('Tarde de jogos', 'Passei a tarde jogando videogame. Às vezes precisamos voltar a ser criança e simplesmente nos divertir.', '2024-01-28', 'divertido', ARRAY['jogos', 'diversao', 'infancia']),
('Planejamento futuro', 'Passei um tempo pensando nos meus planos para os próximos meses. É importante ter objetivos claros.', '2024-01-29', 'determinado', ARRAY['planejamento', 'futuro', 'objetivos']),
('Gratidão diária', 'Hoje decidi praticar mais a gratidão. Listei 10 coisas pelas quais sou grato. O exercício foi libertador.', '2024-01-30', 'grato', ARRAY['gratidao', 'exercicio', 'positivo']),
('Fim de um ciclo', 'Janeiro está acabando. Foi um mês de descobertas, aprendizados e crescimento pessoal. Ansioso pelo que vem!', '2024-01-31', 'esperancoso', ARRAY['fim', 'ciclo', 'crescimento']),
('Novo mês', 'Fevereiro chegou! Tempo de renovar as energias e continuar perseguindo meus sonhos com determinação.', '2024-02-01', 'determinado', ARRAY['novo-mes', 'energia', 'sonhos']),
('Café da manhã especial', 'Preparei um café da manhã elaborado hoje. Pequenos rituais fazem toda a diferença no nosso dia.', '2024-02-02', 'satisfeito', ARRAY['cafe', 'ritual', 'manha']),
('Lição aprendida', 'Cometi um erro hoje, mas aprendi muito com ele. Os erros são nossos melhores professores.', '2024-02-03', 'reflexivo', ARRAY['erro', 'aprendizado', 'licao']),
('Criatividade em alta', 'Tive várias ideias criativas hoje. Escrevi tudo para não esquecer. A inspiração vem quando menos esperamos.', '2024-02-04', 'criativo', ARRAY['ideias', 'criatividade', 'inspiracao']),
('Momento zen', 'Pratiquei meditação pela primeira vez em muito tempo. A paz interior é um tesouro que carregamos dentro de nós.', '2024-02-05', 'zen', ARRAY['meditacao', 'paz', 'interior']),
('Risada contagiante', 'Assisti a uma comédia que me fez rir até doer a barriga. O riso realmente é o melhor remédio.', '2024-02-06', 'alegre', ARRAY['comedia', 'riso', 'humor']),
('Organização total', 'Passei o dia organizando documentos e arquivos. Uma vida organizada é uma mente tranquila.', '2024-02-07', 'organizado', ARRAY['organizacao', 'documentos', 'tranquilidade']),
('Conexão digital', 'Fiz uma videochamada com um amigo que mora longe. A tecnologia nos aproxima mesmo à distância.', '2024-02-08', 'conectado', ARRAY['videochamada', 'amigo', 'tecnologia']),
('Sabor da infância', 'Comi um doce que me lembrou da minha infância. Os sabores têm o poder de nos transportar no tempo.', '2024-02-09', 'nostalgico', ARRAY['doce', 'infancia', 'memoria']),
('Desafio aceito', 'Me propus um novo desafio hoje. Sair da zona de conforto é essencial para o crescimento pessoal.', '2024-02-10', 'corajoso', ARRAY['desafio', 'zona-conforto', 'crescimento']),
('Música no coração', 'Ouvi uma música que me emocionou profundamente. A música toca nossa alma de forma única.', '2024-02-11', 'emocionado', ARRAY['musica', 'emocao', 'alma']),
('Limpeza mental', 'Fiz uma limpeza mental hoje, liberando pensamentos negativos. Nossa mente também precisa de faxina.', '2024-02-12', 'renovado', ARRAY['limpeza', 'mental', 'negativo']),
('Pequenos prazeres', 'Desfrutei de pequenos prazeres hoje: um café quente, um livro bom, uma música suave.', '2024-02-13', 'satisfeito', ARRAY['prazeres', 'cafe', 'livro']),
('Energia renovada', 'Acordei com muita energia hoje. Quando nosso corpo e mente estão alinhados, tudo flui melhor.', '2024-02-14', 'energizado', ARRAY['energia', 'alinhamento', 'fluxo']),
('Memórias afetivas', 'Folheei um álbum de fotos antigas. As memórias são tesouros que guardamos no coração.', '2024-02-15', 'nostalgico', ARRAY['fotos', 'memorias', 'tesouros']),
('Aprendizado constante', 'Aprendi algo novo hoje em uma conversa casual. Cada pessoa que encontramos pode nos ensinar algo.', '2024-02-16', 'curioso', ARRAY['aprendizado', 'conversa', 'ensino']),
('Momento presente', 'Pratiquei viver o momento presente hoje, sem pensar no passado ou futuro. O agora é tudo que temos.', '2024-02-17', 'presente', ARRAY['momento', 'presente', 'mindfulness']),
('Força interior', 'Enfrentei uma situação difícil hoje com coragem. Descobri que sou mais forte do que imaginava.', '2024-02-18', 'forte', ARRAY['forca', 'coragem', 'superacao']),
('Beleza simples', 'Admirei a beleza de uma flor no jardim. A natureza nos ensina sobre simplicidade e perfeição.', '2024-02-19', 'admirado', ARRAY['flor', 'beleza', 'natureza']),
('Fevereiro se despede', 'Último dia de fevereiro. Foi um mês de descobertas internas e crescimento emocional.', '2024-02-29', 'reflexivo', ARRAY['fevereiro', 'descobertas', 'crescimento']);

ALTER TABLE diary_entries ADD COLUMN photo TEXT;
