CREATE DATABASE entrepaginas;

\c entrepaginas;

CREATE TABLE diary_entries (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    entry_date DATE NOT NULL DEFAULT CURRENT_DATE,
    mood VARCHAR(50),
    tags TEXT[],
    photo TEXT,
    is_favorite BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO diary_entries (title, content, entry_date, mood, tags) VALUES
('Meu primeiro dia', 'Hoje foi um dia muito especial, o primeiro dia do meu diario digital! Estou animado para comecar a documentar minha jornada.', '2024-01-01', 'feliz', ARRAY['primeiro-dia', 'especial', 'inicio']),
('Reflexoes da manha', 'Acordei pensando sobre os objetivos para este ano. Quero me dedicar mais aos estudos e cuidar melhor da minha saude.', '2024-01-02', 'reflexivo', ARRAY['manha', 'objetivos', 'saude']),
('Um dia tranquilo', 'Hoje foi um dia calmo, sem muitos acontecimentos. As vezes esses dias sao os melhores para relaxar.', '2024-01-03', 'tranquilo', ARRAY['calmo', 'paz', 'relaxamento']),
('Aventura no parque', 'Sai para caminhar no parque hoje. A natureza sempre me traz uma sensacao de paz e renovacao.', '2024-01-04', 'energizado', ARRAY['natureza', 'caminhada', 'parque']),
('Dia de trabalho intenso', 'O trabalho esteve bem corrido hoje. Muitas reunioes e prazos apertados, mas consegui dar conta de tudo.', '2024-01-05', 'estressado', ARRAY['trabalho', 'reunioes', 'prazos']),
('Encontro com amigos', 'Encontrei meus amigos da faculdade hoje. Foi otimo relembrar os velhos tempos e colocar o papo em dia.', '2024-01-06', 'alegre', ARRAY['amigos', 'faculdade', 'nostalgia']),
('Domingo de descanso', 'Domingo perfeito para ficar em casa, assistir filmes e nao fazer nada produtivo. As vezes e necessario.', '2024-01-07', 'relaxado', ARRAY['descanso', 'filmes', 'casa']),
('Nova descoberta', 'Descobri um novo hobby hoje: pintura! Comprei alguns materiais basicos e ja fiz minha primeira obra.', '2024-01-08', 'entusiasmado', ARRAY['hobby', 'pintura', 'arte']),
('Dia chuvoso', 'Choveu o dia todo. Aproveitei para ler um livro que estava pendente ha meses. A chuva tem algo de poetico.', '2024-01-09', 'contemplativo', ARRAY['chuva', 'leitura', 'livro']),
('Reuniao familiar', 'Almoco em familia hoje. Sempre bom estar com as pessoas que amamos e compartilhar boas historias.', '2024-01-10', 'grato', ARRAY['familia', 'almoco', 'amor']),
('Desafio superado', 'Consegui terminar aquele projeto dificil no trabalho. A sensacao de conquista e indescritivel!', '2024-01-11', 'realizado', ARRAY['projeto', 'conquista', 'trabalho']),
('Noite estrelada', 'Subi no terraco para observar as estrelas. O universo e tao vasto e misterioso. Me senti pequeno e grato.', '2024-01-12', 'inspirado', ARRAY['estrelas', 'universo', 'gratidao']),
('Aula de culinaria', 'Tentei fazer uma receita nova hoje. Nao ficou perfeita, mas foi divertido experimentar na cozinha.', '2024-01-13', 'divertido', ARRAY['culinaria', 'receita', 'experimenta']),
('Dia de folga', 'Finalmente um dia livre! Aproveitei para organizar o quarto e fazer aquela faxina que estava adiando.', '2024-01-14', 'produtivo', ARRAY['organizacao', 'limpeza', 'casa']),
('Conversa profunda', 'Tive uma conversa muito interessante com um colega sobre filosofia e proposito de vida. Me fez pensar muito.', '2024-01-15', 'pensativo', ARRAY['filosofia', 'proposito', 'conversa']),
('Exercicio matinal', 'Acordei cedo para fazer exercicios. Comecar o dia assim deixa tudo mais energizado e produtivo.', '2024-01-16', 'energizado', ARRAY['exercicio', 'manha', 'energia']),
('Visita ao museu', 'Fui ao museu de arte moderna. Algumas obras realmente me tocaram e me fizeram ver a arte de forma diferente.', '2024-01-17', 'inspirado', ARRAY['museu', 'arte', 'cultura']),
('Dia dificil', 'Hoje nao foi um bom dia. Varias coisas deram errado, mas sei que amanha sera melhor. E importante aceitar os dias ruins.', '2024-01-18', 'triste', ARRAY['dificil', 'problemas', 'superacao']),
('Novo aprendizado', 'Comecei um curso online de programacao. Sempre quis aprender e finalmente dei o primeiro passo!', '2024-01-19', 'motivado', ARRAY['curso', 'programacao', 'aprendizado']),
('Passeio na praia', 'Fui a praia no final da tarde. O som das ondas e o por do sol criaram um momento magico de paz interior.', '2024-01-20', 'sereno', ARRAY['praia', 'por-do-sol', 'paz']),
('Reflexao noturna', 'Antes de dormir, sempre gosto de refletir sobre o dia. Hoje foi cheio de pequenas alegrias e aprendizados.', '2024-01-21', 'grato', ARRAY['reflexao', 'gratidao', 'aprendizado']),
('Projeto pessoal', 'Comecei a trabalhar em um projeto pessoal que tenho em mente ha anos. E emocionante tirar ideias do papel!', '2024-01-22', 'empolgado', ARRAY['projeto', 'pessoal', 'ideias']),
('Encontro casual', 'Encontrei um antigo professor na rua hoje. Foi bom conversar e lembrar dos tempos de escola.', '2024-01-23', 'nostalgico', ARRAY['professor', 'escola', 'encontro']),
('Dia de spa caseiro', 'Decidi fazer um dia de autocuidado em casa. Mascara facial, banho relaxante e musica suave.', '2024-01-24', 'relaxado', ARRAY['autocuidado', 'relaxamento', 'spa']),
('Inspiracao literaria', 'Li um poema hoje que me tocou profundamente. A literatura tem o poder de nos transformar por dentro.', '2024-01-25', 'tocado', ARRAY['poesia', 'literatura', 'inspiracao']),
('Caminhada matinal', 'Sai para caminhar bem cedo. As ruas vazias e o ar fresco da manha me deram uma sensacao de liberdade.', '2024-01-26', 'livre', ARRAY['caminhada', 'manha', 'liberdade']),
('Descoberta musical', 'Descobri uma banda nova que esta fazendo meu estilo musical. A musica e realmente universal.', '2024-01-27', 'animado', ARRAY['musica', 'banda', 'descoberta']),
('Tarde de jogos', 'Passei a tarde jogando videogame. As vezes precisamos voltar a ser crianca e simplesmente nos divertir.', '2024-01-28', 'divertido', ARRAY['jogos', 'diversao', 'infancia']),
('Planejamento futuro', 'Passei um tempo pensando nos meus planos para os proximos meses. E importante ter objetivos claros.', '2024-01-29', 'determinado', ARRAY['planejamento', 'futuro', 'objetivos']),
('Gratidao diaria', 'Hoje decidi praticar mais a gratidao. Listei 10 coisas pelas quais sou grato. O exercicio foi libertador.', '2024-01-30', 'grato', ARRAY['gratidao', 'exercicio', 'positivo']),
('Fim de um ciclo', 'Janeiro esta acabando. Foi um mes de descobertas, aprendizados e crescimento pessoal. Ansioso pelo que vem!', '2024-01-31', 'esperancoso', ARRAY['fim', 'ciclo', 'crescimento']),
('Novo mes', 'Fevereiro chegou! Tempo de renovar as energias e continuar perseguindo meus sonhos com determinacao.', '2024-02-01', 'determinado', ARRAY['novo-mes', 'energia', 'sonhos']),
('Cafe da manha especial', 'Preparei um cafe da manha elaborado hoje. Pequenos rituais fazem toda a diferenca no nosso dia.', '2024-02-02', 'satisfeito', ARRAY['cafe', 'ritual', 'manha']),
('Licao aprendida', 'Cometi um erro hoje, mas aprendi muito com ele. Os erros sao nossos melhores professores.', '2024-02-03', 'reflexivo', ARRAY['erro', 'aprendizado', 'licao']),
('Criatividade em alta', 'Tive varias ideias criativas hoje. Escrevi tudo para nao esquecer. A inspiracao vem quando menos esperamos.', '2024-02-04', 'criativo', ARRAY['ideias', 'criatividade', 'inspiracao']),
('Momento zen', 'Pratiquei meditacao pela primeira vez em muito tempo. A paz interior e um tesouro que carregamos dentro de nos.', '2024-02-05', 'zen', ARRAY['meditacao', 'paz', 'interior']),
('Risada contagiante', 'Assisti a uma comedia que me fez rir ate doer a barriga. O riso realmente e o melhor remedio.', '2024-02-06', 'alegre', ARRAY['comedia', 'riso', 'humor']),
('Organizacao total', 'Passei o dia organizando documentos e arquivos. Uma vida organizada e uma mente tranquila.', '2024-02-07', 'organizado', ARRAY['organizacao', 'documentos', 'tranquilidade']),
('Conexao digital', 'Fiz uma videochamada com um amigo que mora longe. A tecnologia nos aproxima mesmo a distancia.', '2024-02-08', 'conectado', ARRAY['videochamada', 'amigo', 'tecnologia']),
('Sabor da infancia', 'Comi um doce que me lembrou da minha infancia. Os sabores tem o poder de nos transportar no tempo.', '2024-02-09', 'nostalgico', ARRAY['doce', 'infancia', 'memoria']),
('Desafio aceito', 'Me propus um novo desafio hoje. Sair da zona de conforto e essencial para o crescimento pessoal.', '2024-02-10', 'corajoso', ARRAY['desafio', 'zona-conforto', 'crescimento']),
('Musica no coracao', 'Ouvi uma musica que me emocionou profundamente. A musica toca nossa alma de forma unica.', '2024-02-11', 'emocionado', ARRAY['musica', 'emocao', 'alma']),
('Limpeza mental', 'Fiz uma limpeza mental hoje, liberando pensamentos negativos. Nossa mente tambem precisa de faxina.', '2024-02-12', 'renovado', ARRAY['limpeza', 'mental', 'negativo']),
('Pequenos prazeres', 'Desfrutei de pequenos prazeres hoje: um cafe quente, um livro bom, uma musica suave.', '2024-02-13', 'satisfeito', ARRAY['prazeres', 'cafe', 'livro']),
('Energia renovada', 'Acordei com muita energia hoje. Quando nosso corpo e mente estao alinhados, tudo flui melhor.', '2024-02-14', 'energizado', ARRAY['energia', 'alinhamento', 'fluxo']),
('Memorias afetivas', 'Folheei um album de fotos antigas. As memorias sao tesouros que guardamos no coracao.', '2024-02-15', 'nostalgico', ARRAY['fotos', 'memorias', 'tesouros']),
('Aprendizado constante', 'Aprendi algo novo hoje em uma conversa casual. Cada pessoa que encontramos pode nos ensinar algo.', '2024-02-16', 'curioso', ARRAY['aprendizado', 'conversa', 'ensino']),
('Momento presente', 'Pratiquei viver o momento presente hoje, sem pensar no passado ou futuro. O agora e tudo que temos.', '2024-02-17', 'presente', ARRAY['momento', 'presente', 'mindfulness']),
('Forca interior', 'Enfrentei uma situacao dificil hoje com coragem. Descobri que sou mais forte do que imaginava.', '2024-02-18', 'forte', ARRAY['forca', 'coragem', 'superacao']),
('Beleza simples', 'Admirei a beleza de uma flor no jardim. A natureza nos ensina sobre simplicidade e perfeicao.', '2024-02-19', 'admirado', ARRAY['flor', 'beleza', 'natureza']),
('Fevereiro se despede', 'Ultimo dia de fevereiro. Foi um mes de descobertas internas e crescimento emocional.', '2024-02-29', 'reflexivo', ARRAY['fevereiro', 'descobertas', 'crescimento']);
